STAF.PATH=/usr/local/staf

install.tar.file.name=sequoiadb_0.1_ubuntu_x64.tar.gz
deploy.tar.file.name=deploy.tar.gz
junitreport.tar.file.name=junit_report.tar.gz
test.machine.deploy.path=/tmp/sequoiadb_test
test.machine.deploy.ip1=192.168.20.201
test.machine.deploy.ip2=192.168.20.202
test.machine.deploy.ip3=192.168.20.202