---
# tmp_local_archive_path 本地暂存目录
#

- name: 'check exist default sequoiadb'
  stat: "path={{ default_env_file }}"
  register: default_sdb_stat

- name: 'get default sdb path'
  shell: "awk -F= '$1==\"INSTALL_DIR\"{print $2}' {{ default_env_file }}"
  register: default_sdb_path
  when: default_sdb_stat.stat.exists

- name: 'set default sdb variable'
  set_fact:
    sdb_conf_local: "{{ default_sdb_path.stdout }}/conf/local"
    sdb_conf_log: "{{ default_sdb_path.stdout }}/conf/log"
    sdb_bin: "{{ default_sdb_path.stdout }}/bin"
  when: default_sdb_stat.stat.exists

- name: create remote archive directory
  file: "path={{ tmp_remote_archive_path }} state=directory"

- name: archive sdb node diaglog
  shell: "tar -zcvf {{ tmp_remote_archive_path }}/diaglog.tar.gz $(grep 'dbpath*' {{ sdb_conf_local }}/*/sdb.conf |awk -F: '{print $2}'|awk -F= '{print $2\"/diaglog\"}')"
  ignore_errors: yes

- name: archive sdb conf local
  archive:
    path: "{{ sdb_conf_local }}"
    dest: "{{ tmp_remote_archive_path }}/sdb_conf.tar.gz"
    owner: sdbadmin
    group: sdbadmin_group
    format: gz
    force_archive: true

- name: archive sdb conf log
  archive:
    path: "{{ sdb_conf_log }}"
    dest: "{{ tmp_remote_archive_path }}/sdb_conf_log.tar.gz"
    owner: sdbadmin
    group: sdbadmin_group
    format: gz
    force_archive: true

- name: archive sdb bin
  shell: "rsync -avp {{ sdb_bin }}/sdb {{ tmp_remote_archive_path }}"

- name: create local receive directory
  file: "path={{ tmp_local_archive_path }}/{{ inventory_hostname }} state=directory"
  delegate_to: localhost

- name: sync remote to local
  synchronize:
    src: "{{ tmp_remote_archive_path }}"
    dest: "{{ tmp_local_archive_path }}/{{ inventory_hostname }}"
    mode: pull

- name: clean remote archive directory
  file: "path={{ tmp_remote_archive_path }} state=absent"
