#!/bin/bash
#the $lines is equal to the number of rows plus 1
lines=621
tail -n +$lines "$0" >/tmp/sequoiadb.tar.gz
CURRENT_TIME=$(date "+%Y-%m-%d_%H:%M:%S")
LOG_FILE=/tmp/install_${CURRENT_TIME}
SYS_TYPE='systemd'
SYS_CONF_FILE=/etc/default/sequoiadb
INSTALLDIR=/opt/sequoiadb
INSTALLMODE=normal
FORCE=false
USERNAME=sdbadmin
GROUPNAME=sdbadmin_group
USERPASSWD=sdbadmin
PORT=11790
PROCESSAUTOSTART=true
SMS=false
PACKAGE_NAME=sequoiadb-3.4-aarch64-enterprise-installer.run
PACKAGE_PATH=/opt/sequoiadb-3.4-aarch64-enterprise-installer.run
BACKUPDIR=""
SERVICE_ORIGIN_STATUS=0
SERVICE_STATUS=false
GLIBCXX_VERSION="GLIBCXX_VERSION_VALUE"
GIT_VERSION="GIT_VERSION_VALUE"
BUILD_TIME="BUILD_TIME_VALUE"
OLD_VERSION=""
NEW_VERSION=""
OLD_RELEASE=0
NEW_RELEASE=0
OLD_EDITION_FULL=Community
NEW_EDITION_FULL=Community
HAS_OM=false
IsGeneral=TRUE
OMAddress=''

function checkUmask()
{
   local other_mask=`umask | awk '{print substr($0,length($0)-0,1)}'`
   local group_mask=`umask | awk '{print substr($0,length($0)-1,1)}'`
   local user_mask=`umask | awk '{print substr($0,length($0)-2,1)}'`
   local full_mask=`umask`
   if [ ${other_mask} -gt 2 -o ${group_mask} -gt 2 -o ${user_mask} -gt 0 ]; then
      echo "Umask abnormal! Current umask = ${full_mask}, recommended value is 0022" >&2 && exit 1;
   fi
}

function checkFreeDiskSpace()
{
   test -d ${INSTALLDIR} || mkdir -p ${INSTALLDIR}
   local free_disk=`df ${INSTALLDIR} | awk '/[0-9]%/{print $(NF-2)}'`
   if [ ${free_disk} -le 1300000 ];then
      echo "There is not enough disk space for installation. It needs at lease 1.3G" >&2 && exit 1;
   fi
}

function checkHostnameIp()
{
   local machine_hostname=`hostname`
   if [ "${machine_hostname}" == 'localhost' -o "${machine_hostname}" == '(none)' -o "${machine_hostname}" == '' ]; then
      echo "Hostname may be null!" >&2 && exit 1;
   fi
   local machine_ip=`ip a | grep -w 'inet'|grep 'global'| awk '{print $2}' | awk -F / '{print $1}'`
   local hostname_ip=`hostname -i`
   echo "${machine_ip}" | grep -q "${hostname_ip}"
   if [ $? != 0 ]; then
      echo "The ip(${hostname_ip}) of host(${machine_hostname}) does not match any ip(${machine_ip}) of network adapter! Please check file '/etc/hosts' and run command 'ip a' for more detail."  >&2 && exit 1;
   fi
}

function checkCompatible()
{
   mkdir -p ${INSTALLDIR}/tmp_${CURRENT_TIME}
   tar -xf /tmp/sequoiadb.tar.gz -C ${INSTALLDIR}/tmp_${CURRENT_TIME} compatible.sh
   tar -xf /tmp/sequoiadb.tar.gz -C ${INSTALLDIR}/tmp_${CURRENT_TIME} version.conf
   tar -xf /tmp/sequoiadb.tar.gz -C ${INSTALLDIR}/tmp_${CURRENT_TIME} bin/sequoiadb
   chmod 755 ${INSTALLDIR}/tmp_${CURRENT_TIME}/compatible.sh
   chmod 755 ${INSTALLDIR}/tmp_${CURRENT_TIME}/bin/sequoiadb
   OLD_VERSION=`${INSTALLDIR}/bin/sequoiadb --version | grep -v "Git" | grep "version" | awk '{print $3}'`
   OLD_RELEASE=`${INSTALLDIR}/bin/sequoiadb --version | grep "Release" | awk '{print $2}'`
   local old_is_enterprise=`${INSTALLDIR}/bin/sequoiadb --version | grep -i enterprise | wc -l`
   local old_edition=C
   OLD_EDITION_FULL=Community
   test ${old_is_enterprise} -ne 0 && old_edition=E
   test ${old_is_enterprise} -ne 0 && OLD_EDITION_FULL=Enterprise
   NEW_VERSION=`${INSTALLDIR}/tmp_${CURRENT_TIME}/bin/sequoiadb --version | grep -v "Git" | grep "version" | awk '{print $3}'`
   NEW_RELEASE=`${INSTALLDIR}/tmp_${CURRENT_TIME}/bin/sequoiadb --version | grep "Release" | awk '{print $2}'`
   local new_is_enterprise=`${INSTALLDIR}/tmp_${CURRENT_TIME}/bin/sequoiadb --version | grep -i enterprise | wc -l`
   local new_edition=C
   NEW_EDITION_FULL=Community
   test ${new_is_enterprise} -ne 0 && new_edition=E
   test ${old_is_enterprise} -ne 0 && NEW_EDITION_FULL=Enterprise
   local compatible_ret=`${INSTALLDIR}/tmp_${CURRENT_TIME}/compatible.sh ${OLD_VERSION} ${old_edition} ${NEW_VERSION} ${new_edition} --db`
   rm -rf ${INSTALLDIR}/tmp_${CURRENT_TIME}
   if [[ ${compatible_ret} != true ]]; then
      echo "You can't upgrade from version ${OLD_VERSION} ${OLD_EDITION_FULL} to ${NEW_VERSION} ${NEW_EDITION_FULL}, for the compatibility" >&2 && exit 1;
   fi
}

function exist_installation()
{
   if test -s ${SYS_CONF_FILE}; then
      INSTALLDIR=`grep 'INSTALL_DIR' /etc/default/sequoiadb | awk -F = '{print $2}'`
      return 0;
   elif [ ${INSTALLMODE} == "upgrade" ]; then
      echo "File ${SYS_CONF_FILE} does not exist" >&2 && exit 1;
   fi
   
   return 1;
}

function linkPhpLib()
{
   local php_lib_dir=${INSTALLDIR}/tools/server/php/libxml2/lib
   
   rm -rf ${php_lib_dir}/libxml2.so
   ln -s ${php_lib_dir}/libxml2.so.2.9.0 ${php_lib_dir}/libxml2.so
   chown -h ${USERNAME}:${GROUPNAME} ${php_lib_dir}/libxml2.so
   
   rm -rf ${php_lib_dir}/libxml2.so.2
   ln -s ${php_lib_dir}/libxml2.so.2.9.0 ${php_lib_dir}/libxml2.so.2
   chown -h ${USERNAME}:${GROUPNAME} ${php_lib_dir}/libxml2.so.2
   
   rm -rf ${php_lib_dir}/libz.so
   ln -s ${php_lib_dir}/libz.so.1.2.5 ${php_lib_dir}/libz.so
   chown -h ${USERNAME}:${GROUPNAME} ${php_lib_dir}/libz.so
   
   rm -rf ${php_lib_dir}/libz.so.1
   ln -s ${php_lib_dir}/libz.so.1.2.5 ${php_lib_dir}/libz.so.1
   chown -h ${USERNAME}:${GROUPNAME} ${php_lib_dir}/libz.so.1
}

function changePermissionOwner()
{
   chmod 755 ${INSTALLDIR}/bin/{*,*/*} 
   chmod 755 ${INSTALLDIR}/plugins/SequoiaSQL/bin/*.sh 
   chmod 755 ${INSTALLDIR}/tools/server/php/bin/* 
   chmod 755 ${INSTALLDIR}/tools/expect/bin/*
   chmod 755 ${INSTALLDIR}/tools/deploy/quickDeploy.sh
   chmod 744 ${INSTALLDIR}/tools/dr_ha/*.sh
   chmod 744 ${INSTALLDIR}/tools/expect/trust/trustRelpConf.sh
   chmod 744 ${INSTALLDIR}/tools/sdbmigrate/bin/*.sh
   chmod 744 ${INSTALLDIR}/tools/sequoiafs/bin/*.sh
   chmod 744 ${INSTALLDIR}/tools/sequoias3/sequoias3.sh
   chmod 744 ${INSTALLDIR}/tools/ptmallocstats/ptmalloc_stats.py
   chmod 744 ${INSTALLDIR}/tools/sdbaudit/sdbaudit_ctl.py
   chmod 744 ${INSTALLDIR}/tools/sdbaudit/sdbaudit_daemon.py
   chmod 744 ${INSTALLDIR}/tools/sdbsupport/sdbsupport.sh
   chmod 744 ${INSTALLDIR}/tools/crontask/sdbtaskctl
   chmod 744 ${INSTALLDIR}/tools/crontask/sdbtaskdaemon
   chmod 755 ${INSTALLDIR}/www/shell/* 
   chmod 755 ${INSTALLDIR}/install_om.sh
   chmod 755 ${INSTALLDIR}/compatible.sh
   chmod 755 ${INSTALLDIR}/preUninstall.sh
   chmod 755 ${INSTALLDIR}/conf/script/*/*.sh
   chmod 755 ${INSTALLDIR}/java/jdk/bin/*
   chmod 755 ${INSTALLDIR}/postgresql/*.so*
   chmod 777 /tmp
   test -f /tmp/sequoiadb && chmod 777 /tmp/sequoiadb
   chown root:root ${INSTALLDIR}/bin/sdbomtool
   chown root:root ${INSTALLDIR}/uninstall
   chmod 755 ${INSTALLDIR}/uninstall
   chmod 6755 ${INSTALLDIR}/bin/sdbomtool 
   setcap 'CAP_SYS_RESOURCE=+ep' ${INSTALLDIR}/bin/sdbstart
   setcap 'CAP_SYS_RESOURCE=+ep' ${INSTALLDIR}/bin/sdbcmart
   setcap 'CAP_SYS_RESOURCE=+ep' ${INSTALLDIR}/bin/stpstart
   setcap 'CAP_SYS_RESOURCE=+ep' ${INSTALLDIR}/bin/stp
   rm -f ${INSTALLDIR}/www/doc
   ln -s ${INSTALLDIR}/doc ${INSTALLDIR}/www/doc
   chown -h ${USERNAME}:${GROUPNAME} ${INSTALLDIR}/www/doc
   mkdir -p /var/sequoiadb 
   chown ${USERNAME}:${GROUPNAME} /var/sequoiadb
   chmod 777 /var/sequoiadb
}

function startService()
{
   systemctl daemon-reload
   service sdbcm start >> /dev/null 2>&1
   test $? -ne 0 && echo "Failed to start cm, execute: service sdbcm start." >&2 && return 1;
   return 0;
}

function stopService()
{
   service sdbcm stop >> /dev/null 2>&1
   test $? -ne 0 && echo "Failed to stop cm, execute: service sdbcm stop." >&2 && exit 1;
   su - ${USERNAME} -c "${INSTALLDIR}/bin/sdbcmtop" >> /dev/null
   su - ${USERNAME} -c "${INSTALLDIR}/bin/sdbstop -t all" >> /dev/null
   local process_num=`${INSTALLDIR}/bin/sdblist -t all | grep -v "Total" | wc -l`
   test ${process_num} -gt 0 && echo "Relevant processes still exist after excuting 'service sdbcm stop'." >&2 && exit 1;
   return 0;
}

function addEnv()
{
   local envFile=$1
   grep -q "^export PATH=\"\$PATH:${INSTALLDIR}/bin\"$" ${envFile}
   test $? -ne 0 && echo "export PATH=\"\$PATH:${INSTALLDIR}/bin\"" >> ${envFile}
   
   grep -q "^export LD_LIBRARY_PATH=\"\$LD_LIBRARY_PATH:${INSTALLDIR}/lib\"$" ${envFile}
   test $? -ne 0 && echo "export LD_LIBRARY_PATH=\"\$LD_LIBRARY_PATH:${INSTALLDIR}/lib\"" >> ${envFile}
}

function getSysType()
{
   SYS_TYPE=`ls -l /proc/1/exe | awk -F / '{print $NF}'`
}

function addSystemdService()
{
   local install_dir_reg="$(echo "${INSTALLDIR}" | sed 's/\//\\\//g')"
   sed -i "s/\/opt\/sequoiadb/${install_dir_reg}/" ${INSTALLDIR}/sdbcm.service
   test -d /usr/lib/systemd/system && cp ${INSTALLDIR}/sdbcm.service /usr/lib/systemd/system
   test -d /lib/systemd/system && cp ${INSTALLDIR}/sdbcm.service /lib/systemd/system
   rm -f ${INSTALLDIR}/sdbcm.service
   systemctl daemon-reload >> /dev/null 2>&1
   test $? -ne 0 && echo "Failed to reload daemon, execute: systemctl daemon-reload." >&2 && exit 1;
   systemctl enable sdbcm.service >> /dev/null 2>&1
   test $? -ne 0 && echo "Failed to enable service, execute: systemctl enable sdbcm.service." >&2 && exit 1;
}

function startOm()
{
   local om_port=11780
   local om_dbpath=${INSTALLDIR}/database/sms/${om_port}
   local http_port=8000
   local installom_mode=normal
   if [ "${INSTALLMODE}" != "normal" -a "${HAS_OM}" == TRUE ]; then
      installom_mode=upgrade
   fi
   ${INSTALLDIR}/install_om.sh ${installom_mode} "${INSTALLDIR}" "${PACKAGE_PATH}" ${PORT} ${om_port} "${om_dbpath}" ${http_port} >>/dev/null
   chown -R ${USERNAME}:${GROUPNAME} ${INSTALLDIR}/packet
}

function stopOM()
{
   su - ${USERNAME} -c "${installdir}/bin/sdbstop -t om -r om"
}

function readyToInstall()
{
   #check disk
   checkFreeDiskSpace
   #check hostname and ip
   checkHostnameIp
   #check umask
   checkUmask
   #check install user
   if [ ${USERNAME} == "root" ];then
      echo "The ROOT user is not allowed to create." >&2 && exit 1;
   fi
   #check process has been stoped or not
   if [ ${INSTALLMODE} == "cover" ]; then
      local user_in_conf=`grep 'SDBADMIN_USER' /etc/default/sequoiadb | awk -F = '{print $2}'`
      if [ "${USERNAME}" != "${user_in_conf}" -a "${user_in_conf}" != '' ]; then
         echo "ERROR: The specified user is different from the original installation user." >&2 && exit 1;
      fi
      HAS_OM=`grep "IsGeneral" ${INSTALLDIR}/conf/sdbcm.conf | awk -F = '{print $2}'`
      if [ "${HAS_OM}" == TRUE ]; then
         IsGeneral=`grep "IsGeneral" ${INSTALLDIR}/conf/sdbcm.conf | awk -F = '{print $2}'`
         OMAddress=`grep "OMAddress" ${INSTALLDIR}/conf/sdbcm.conf | awk -F = '{print $2}'`
      fi
      service sdbcm status >> /dev/null 2>&1
      SERVICE_ORIGIN_STATUS=$?
      if [ ${SMS} != "only" ]; then
         test ${SERVICE_ORIGIN_STATUS} -eq 0 && stopService
      else
         test ${SERVICE_ORIGIN_STATUS} -eq 0 && service sdbcm stop >> /dev/null 2>&1
         test $? -ne 0 && echo "Failed to stop cm, execute: service sdbcm stop." >&2 && exit 1;
         su - ${USERNAME} -c "${INSTALLDIR}/bin/sdbcmtop" >> /dev/null 2>&1
         test $? -ne 0 && echo "Failed to stop sdbcm, execute: bin/sdbcmtop." >&2 && exit 1;
      fi
   fi
   #check or create user group
   local exist_user=false
   local exist_group=false
   `grep "^${USERNAME}:" /etc/passwd >> /dev/null` 
   test $? -eq 0 && exist_user=true
   `grep "^${GROUPNAME}:" /etc/group  >> /dev/null`
   test $? -eq 0 && exist_group=true
   if [ ${exist_user} == true ]
   then
      local act_group=`id -ng ${USERNAME}`
      if [ "${act_group}" != "${GROUPNAME}" ];then
         echo "User ${USERNAME} exists, but it does not belong to group ${GROUPNAME}" >&2 && exit 1;
      fi
   else
      if [ ${exist_group} == false ]; then
         `groupadd ${GROUPNAME}`
      fi
      local bash_path=`which bash`
      `useradd ${USERNAME} -m -g ${GROUPNAME} -s ${bash_path}`
      `passwd --help | grep stdin >> /dev/null`
      if [ $? == 0 ]
      then
         `echo "${USERPASSWD}" | passwd --stdin ${USERNAME} >> /dev/null`
      else
         `echo -e "${USERPASSWD}\n${USERPASSWD}" | passwd ${USERNAME} >> /dev/null`
      fi
   fi
   
}

function readyToUpgrade()
{
   #check install user
   if [ ${USERNAME} == "root" ];then
      echo "The ROOT user is not allowed to create." >&2 && exit 1;
   fi
   #check installdir
   if [ ! -d ${INSTALLDIR} ]; then
      echo "Install dir ${INSTALLDIR} not-existed" >&2
      exit 1;
   fi
   if [[ "`ls -A ${INSTALLDIR}`" == "" ]]; then 
      echo "Install dir ${INSTALLDIR} is empty" >&2
      exit 1;
   fi
   #check sequoiadb
   if [ ! -s ${INSTALLDIR}/bin/sequoiadb ]; then
      echo "${INSTALLDIR}/bin/sequoiadb does not exist" >&2
      exit 1;
   fi
   #check user
   USERNAME=`grep 'SDBADMIN_USER' /etc/default/sequoiadb | awk -F = '{print $2}'`
   `grep "^${USERNAME}:" /etc/passwd >> /dev/null` 
   test $? -ne 0 && echo "User ${USERNAME} does not exist." >&2 && exit 1;
   GROUPNAME=`id -ng ${USERNAME}`
   #check disk
   checkFreeDiskSpace
   #check hostname and ip
   checkHostnameIp
   #check umask
   checkUmask
   #check OM
   HAS_OM=`grep "IsGeneral" ${INSTALLDIR}/conf/sdbcm.conf | awk -F = '{print $2}'`
   #check process has been stoped or not
   service sdbcm status >> /dev/null 2>&1
   SERVICE_ORIGIN_STATUS=$?
   local process_num=`${INSTALLDIR}/bin/sdblist -t all | grep -v "Total" | wc -l`
   if [ "${SERVICE_ORIGIN_STATUS}" == 0 -o "${process_num}" != 0 -o "${SMS}" ]; then
      if [ ${SMS} != "only" ]; then
         stopService
      else
         service sdbcm stop >> /dev/null 2>&1
         test $? -ne 0 && echo "Failed to stop cm, execute: service sdbcm stop." >&2 && exit 1;
         su - ${USERNAME} -c "${INSTALLDIR}/bin/sdbcmtop" >> /dev/null 2>&1
         test $? -ne 0 && echo "Failed to stop sdbcm, execute: bin/sdbcmtop." >&2 && exit 1;
      fi
   fi  
}

function backupInstallDir()
{
   BACKUPDIR=${INSTALLDIR}/rollback/BackupDir_${CURRENT_TIME}
   su - ${USERNAME} -c "mkdir -p ${BACKUPDIR}${INSTALLDIR}"
   test $? -ne 0 && echo "mkdir backupdir ${BACKUPDIR}${INSTALLDIR} failed." >&2 && return 1;
   su - ${USERNAME} -c "cd ${INSTALLDIR};cp -rf `ls ${INSTALLDIR} | grep -v rollback | grep -v database | xargs` ${BACKUPDIR}${INSTALLDIR}"
   test $? -ne 0 && echo "backup installation to backupdir ${BACKUPDIR} failed." >&2 && return 1;
   return 0;
}

function unpackFile()
{
   test -d ${INSTALLDIR} || mkdir -p ${INSTALLDIR}
   test $? -ne 0 && echo "mkdir installdir ${INSTALLDIR} failed." >&2 && return 1;
   if [ ${SMS} == "only" ]; then
      rm -rf ${INSTALLDIR}/bin/*
   fi
   touch ${INSTALLDIR}/uninstall.dat
   tar -zxvf /tmp/sequoiadb.tar.gz -C ${INSTALLDIR} >> ${INSTALLDIR}/uninstall.dat
   test $? -ne 0 && echo "failed to unpack the installation package." >&2 && return 1;
   chown -R ${USERNAME}:${GROUPNAME} ${INSTALLDIR}
   test $? -ne 0 && echo "failed to modify the user to which the installation directory belongs" >&2 && return 1;
   rm -rf /tmp/sequoiadb.tar.gz
   return 0;
}

function postInstallation()
{
   linkPhpLib
   changePermissionOwner
   #modify tcp
   test -f /proc/sys/net/ipv4/tcp_retries2 && echo 3 >> /proc/sys/net/ipv4/tcp_retries2
   #write /etc/default/sequoiadb
   rm -f ${SYS_CONF_FILE}
   touch ${SYS_CONF_FILE}
   chown ${USERNAME}:${GROUPNAME} ${SYS_CONF_FILE}
   chmod 0644 ${SYS_CONF_FILE}
   local md5=`md5sum ${PACKAGE_PATH} | cut -c 1-32`
   echo NAME=sdbcm >> ${SYS_CONF_FILE}
   echo SDBADMIN_USER=${USERNAME} >> ${SYS_CONF_FILE}
   echo INSTALL_DIR=${INSTALLDIR} >> ${SYS_CONF_FILE}
   echo MD5=${md5} >> ${SYS_CONF_FILE}
   #write conf/sdbcm.conf
   if [ "${HAS_OM}" == TRUE ]; then
      echo IsGeneral=${IsGeneral} >> ${INSTALLDIR}/conf/sdbcm.conf
      echo OMAddress=${OMAddress} >> ${INSTALLDIR}/conf/sdbcm.conf
   fi
   local user_home=`grep "^${USERNAME}:" /etc/passwd | awk -F : '{print $6}'`
   touch ${user_home}/.bashrc
   chown -R ${USERNAME}:${GROUPNAME} ${user_home}/.bashrc
   local env1_exists=false
   local env2_exists=false
   test -f ${user_home}/.bash_profile && env1_exists=true
   test -f ${user_home}/.profile && env2_exists=true
   if [ ${env1_exists} == false -a ${env2_exists} == false ]
   then
      touch ${user_home}/.bash_profile
   fi
   test -f ${user_home}/.bash_profile && chown -R ${USERNAME}:${GROUPNAME} ${user_home}/.bash_profile
   addEnv ${user_home}/.bashrc
   test -f ${user_home}/.bash_profile && addEnv ${user_home}/.bash_profile
   test -f ${user_home}/.profile && addEnv ${user_home}/.profile
   getSysType 
   if [ ${SYS_TYPE} == "systemd" ];then
      addSystemdService
   fi
   startService
   test $? -ne 0 && exit 1;
   if [ ${SMS} == true -o ${SMS} == "only" -o "${HAS_OM}" == TRUE ];then
      startOm
   fi
   rm -f ${INSTALLDIR}/sequoiadb.tar.gz
}

function postUpgrade()
{
   linkPhpLib
   changePermissionOwner
   #write /etc/default/sequoiadb
   local md5=`md5sum ${PACKAGE_PATH} | cut -c 1-32`
   sed -i "s/MD5.*$/MD5=${md5}/g" /etc/default/sequoiadb
   #restore the old configuration
   su - ${USERNAME} -c "cp -f ${BACKUPDIR}/${INSTALLDIR}/conf/limits.conf ${INSTALLDIR}/conf/limits.conf"
   su - ${USERNAME} -c "cp -f ${BACKUPDIR}/${INSTALLDIR}/conf/sdbcm.conf ${INSTALLDIR}/conf/sdbcm.conf"
   #write an upgrade log
   test -s ${INSTALLDIR}/upgrade.log || su - ${USERNAME} -c "touch ${INSTALLDIR}/upgrade.log" >&2
   echo "time: ${CURRENT_TIME}" >> ${INSTALLDIR}/upgrade.log
   echo "upgrade from version ${OLD_VERSION} ${OLD_EDITION_FULL} (release ${OLD_RELEASE}) to ${NEW_VERSION} ${NEW_EDITION_FULL} (release ${NEW_RELEASE})" >> ${INSTALLDIR}/upgrade.log 
   getSysType 
   if [ ${SYS_TYPE} == "systemd" ];then
      addSystemdService
   fi
   startService
   test $? -ne 0 && exit 1;
   if [ ${SMS} == true -o ${SMS} == "only" -o "${HAS_OM}" == TRUE ];then
      startOm
   fi
   #start all node
   su - ${USERNAME} -c "${INSTALLDIR}/bin/sdbstart -t all" >> /dev/null
   test $? -ne 0 && echo "Warn: Some nodes failed to start, please see ${INSTALLDIR}/conf/sdbcm.log for details" >&2
   su - ${USERNAME} -c "${INSTALLDIR}/bin/sdbcmart" >> /dev/null
   test $? -ne 0 && echo "Warn: Failed to start sdbcm, please see ${INSTALLDIR}/conf/sdbcm.log for details" >&2
   rm -f ${INSTALLDIR}/sequoiadb.tar.gz
   return 0;
}

function rollbackUpgrade()
{
   echo "Begin to rollback upgrade." >&2
   su - ${USERNAME} -c "cp -rfp ${BACKUPDIR}/${INSTALLDIR}/* ${INSTALLDIR}/"
   test $? -ne 0 && echo "rollback upgrade failed: copy ${BACKUPDIR}/${INSTALLDIR} to ${INSTALLDIR} failed." >&2 && exit 1;
   if [ ${SERVICE_ORIGIN_STATUS} == 0 ]; then
      startService
      test $? -ne 0 && exit 1;
   fi
   rm -rf ${BACKUPDIR}
   echo "Rollback upgrade success." >&2
}

function normalComponent()
{
   readyToInstall
   unpackFile
   test $? -ne 0 && echo "Failed to unpack the installation package." >&2 && exit 1;
   postInstallation
   echo "SequoiaDB installation complete. The program is installed in the ${INSTALLDIR}" >&2
}

function upgradeComponent()
{
   readyToUpgrade
   checkCompatible
   backupInstallDir
   test $? -ne 0 && echo "backup installation failed." >&2 && exit 1;
   unpackFile
   test $? -ne 0 && echo "unpack the installation package failed." >&2 && rollbackUpgrade && exit 1;
   postUpgrade
   test $? -ne 0 && echo "upgrade process failed." >&2 && rollbackUpgrade && exit 1;
   echo "SequoiaDB upgrade complete. The program is installed in the ${INSTALLDIR}" >&2
}

function installSDB()
{
   echo "Start installation program ..." >&2
   exist_installation
   if [ $? == 0 -a ${INSTALLMODE} != "cover" ]; then
      upgradeComponent
   else
      normalComponent
   fi
}

function show_version()
{
   echo $GLIBCXX_VERSION
   echo $GIT_VERSION
   echo $BUILD_TIME
}

function build_help()
{
   echo "--version                      Display product information"
   echo "--prefix <prefix>              Installation Directory"
   echo "                               Default: /opt/sequoiadb"
   echo "--installmode <installmode>    Do you want to upgrade or cover"
   echo "                               Default:"
   echo "                               Allowed: upgrade cover"
   echo "--force <force>                Force Installation"
   echo "                               Default: false"
   echo "--username <username>          User Name"
   echo "                               Default: sdbadmin"
   echo "--groupname <groupname>        Group Name"
   echo "                               Default: sdbadmin_group"
   echo "--userpasswd <userpasswd>      Password"
   echo "                               Default: sdbadmin"
   echo "--port <port>                  SequoiaDB Cluster Manager Port"
   echo "                               Default: 11790"
   echo "--processAutoStart <processAutoStart> Do You Want To Start Sequoiadb Processes When Machine Restart?"
   echo "                               Default: true"
   echo "--SMS <SMS>                    Do You Want To Install OM Service?"
   echo "                               Default: false"
   echo "                               Allowed: true false only"

}

ARGS=`getopt -o hv --long help,version,print,prefix:,mode:,installmode:,force:,username:,groupname:,userpasswd:,port:,processAutoStart:,SMS: -n 'install' -- "$@"`
ret=$?
test $ret -ne 0 && exit $ret

eval set -- "${ARGS}"

while true
do
   case "$1" in
      --prefix )                        INSTALLDIR=$2
                                        shift 2
                                        ;;
      --installmode )                   INSTALLMODE=$2
                                        shift 2
                                        ;;
      --mode )                          shift 2
                                        ;;
      --force )                         FORCE=$2
                                        shift 2
                                        ;;
      --username )                      USERNAME=$2
                                        shift 2
                                        ;;
      --groupname )                     GROUPNAME=$2
                                        shift 2
                                        ;;
      --userpasswd )                    USERPASSWD=$2
                                        shift 2
                                        ;;
      --port )                          PORT=$2
                                        shift 2
                                        ;;
      --processAutoStart )              PROCESSAUTOSTART=$2
                                        shift 2
                                        ;;
      --SMS )                           SMS=$2
                                        shift 2
                                        ;;
      -h | --help )                     build_help
                                        exit 0
                                        ;;
      -v | --version )                  show_version
                                        exit 0
                                        ;;
      --)                               shift
                                        break
                                        ;;
      *)                                echo "Internal error!"
                                        exit 64
                                        ;;
   esac
done

#确认是安装还是升级
#校验端口号，true  false值
cur_user=`whoami`
if [ "$cur_user" != "root" ]
then
   echo "ERROR: the installation requires root permission" >&2
   exit 1
fi

#get PACKAGE_PATH
PACKAGE_PATH=$0

#参数校验
if [ "$INSTALLMODE" != normal -a "$INSTALLMODE" != upgrade -a "$INSTALLMODE" != cover ]
then
   echo "ERROR: Invalid value \"$INSTALLMODE\" for --installmode. Allowed values are: upgrade cover" >&2
   exit 1
fi
if [ "$SMS" != true -a "$SMS" != false -a "$SMS" != only ]
then
   echo "ERROR: Invalid value \"$SMS\" for --SMS. Allowed values are: true false only" >&2
   exit 1
fi
if [[ "${INSTALLDIR:0:1}" != "/" ]]; 
then
   INSTALLDIR=$(pwd)/$INSTALLDIR    #absolute path
fi

installSDB
exit 0
